### ISSUE TITLE
Various Artisan Worktables Bugs

### ISSUE THREAD

**Issue by UnicornSnuggler** [codetaylor/artisan-worktables-1.16#2]
1. **The toolbox interface doesn't gray out the background like the other Artisan Worktables GUIs.**
This isn't the biggest deal in the world, but it's definitely a little bit jarring and makes it difficult to see JEI.  Most importantly, though, it's just inconsistent with the other Artisan Worktables GUIs and I'm certain you'd want to be aware of inconsistencies like this!
_Figure A: The toolbox GUI with an unobscured background._
![image](https://user-images.githubusercontent.com/10764837/114810879-9bc2ce80-9d72-11eb-89f7-99698fd45a42.png)
_Figure B: A worktable GUI with an obscured background for comparison._
![image](https://user-images.githubusercontent.com/10764837/114810788-6e762080-9d72-11eb-92ae-5d07e2ccdf59.png)

2. **Item tooltips don't show up while the toolbox is open.**
While the toolbox GUI is open, tooltips will not appear when hovering over items in the toolbox or the player inventory.  Similar in impact and effect to the previous issue — and possibly related in some capacity given the strangeness of these respective behaviors!
_Figure C: Hovering over an item in the toolbox GUI without a tooltip._
![image](https://user-images.githubusercontent.com/10764837/114810974-d0368a80-9d72-11eb-9502-f3194cdf8f4b.png)

3. **The toolbox will only accept three specific types of tools.**
I can only store handsaws, hatchet, and carver tools in the toolbox.  No other tool type is allowed in the toolbox.  Refer to the screenshot associated with the previous issue for verification.  This may or may not be an `Artisan Tools` issue, but I figured it would be safest to just include it here.

4. **Fluid gauges clip through item tooltips.**
The fluid gauges in the worktable and workstation GUIs are clipping through item tooltips.  Curiously enough, the workshop doesn't have a similar issue.
_Figure D: The fluid gauge in the worktable GUI clipping through an item tooltip._
![image](https://user-images.githubusercontent.com/10764837/114811581-f3156e80-9d73-11eb-969e-e209d6662360.png)
_Figure E: The fluid gauge in the workstation GUI clipping through an item tooltip._
![image](https://user-images.githubusercontent.com/10764837/114811500-d37e4600-9d73-11eb-9273-a236791ec5ce.png)
_Figure F: The workshop GUI with no unexpected clipping._
![image](https://user-images.githubusercontent.com/10764837/114811621-0cb6b600-9d74-11eb-9877-dc987bc5d013.png)

**Comment by codetaylor** [comment]
Thanks for the report. In the future, please open a new issue for each separate issue.

**Comment by codetaylor** [comment]
> I can only store handsaws, hatchet, and carver tools in the toolbox.

Correct. Only items that have been declared as tools in an AW recipe are accepted into the toolbox.

**Comment by UnicornSnuggler** [comment]
> Thanks for the report. In the future, please open a new issue for each separate issue.
Ahh, my apologies!  Didn't know whether to spam the repo with tickets or consolidate them into a larger report.  If you'd like, I can split each one up into its own issue?  I know when I develop, I do so on a feature-based release schedule and handling bugs is no different for me.

> > I can only store handsaws, hatchet, and carver tools in the toolbox.
> 
> Correct. Only items that have been declared as tools in an AW recipe are accepted into the toolbox.
Pffffffft I feel like an imbecile for not thinking of this as a factor.  It should have dawned on me after fruitlessly trying to ram the tenth or fifteenth tool into the toolbox that I only have recipes scripted for the three types in question 😂

**Comment by codetaylor** [comment]
> If you'd like, I can split each one up into its own issue?

No, it's fine. I'll work with it the way it is. Having separate tickets for each issue makes it easier for me to track progress on an issue, link relevant changes to an issue, and consolidate discussion around an issue in a single place.
