### ISSUE TITLE
Buckets from the mod Wooden Buckets get turned into iron when pouring liquid into worktables.

### ISSUE THREAD

**Issue by UnicornSnuggler** [codetaylor/artisan-worktables-1.16#4]
It looks like the worktables are scripted in a way such that any bucket-like items are converted into iron buckets when liquid is poured from them into a table.  Specifically, the mod in question is [Wooden Buckets](https://www.curseforge.com/minecraft/mc-mods/wooden-buckets).  A wooden bucket with water is converted into an iron bucket when right-clicking on the worktable.

_Figure A: 1000 mB in the carpenter's worktable with a wooden water bucket in the inventory._
![image](https://user-images.githubusercontent.com/10764837/115321124-d3ea5880-a148-11eb-914b-51f5171a2ee1.png)

_Figure B: 2000 mB of water in the carpenter's worktable with an empty iron bucket in the inventory._
![image](https://user-images.githubusercontent.com/10764837/115321198-f5e3db00-a148-11eb-8d99-be57140fe164.png)

**Comment by codetaylor** [comment]
> any bucket-like items are converted into iron buckets

Can you confirm that this affects more than just the bucket from the Wooden Buckets mod?

**Comment by UnicornSnuggler** [comment]
I installed and tested this bug with [Cermic Bucket](https://www.curseforge.com/minecraft/mc-mods/ceramic-bucket) and it looks like maybe it's not a universal issue considering the expected behavior.  I'm opting not to close this ticket just yet in case the fix is specific to the Wooden Buckets mod rather than this one, but I will cross-post the issue just to be certain that the correct level of oversight exists.

_Figure C: 1000 mB in the carpenter's worktable with a ceramic water bucket in the inventory._
![image](https://user-images.githubusercontent.com/10764837/115324019-bfa95a00-a14e-11eb-8d65-b625bd7ab8f1.png)

_Figure D: 2000 mB of water in the carpenter's worktable with an empty ceramic bucket in the inventory._
![image](https://user-images.githubusercontent.com/10764837/115324117-ef586200-a14e-11eb-8b97-6c1437be3227.png)

**Comment by codetaylor** [comment]
The AW block simply defers to Forge's `FluidUtil` which is:

```
     * Used to handle the common case of a player holding a fluid item and right-clicking on a fluid handler.
     * First it tries to fill the item from the handler,
     * if that action fails then it tries to drain the item into the handler.
     * Automatically updates the item in the player's hand and stashes any extra items created.
```

The onus is on the item stack's fluid handler to provide the correct return item.

**Comment by codetaylor** [comment]
> I'm opting not to close this ticket just yet in case the fix is specific to this mod rather than Wooden Buckets [...]

The Wooden Buckets mod is responsible for the bug and I am going to close this issue now.
